version: 0.2

env:
  variables:
    AWS_REGION: "us-east-1"
    AWS_ACCOUNT_ID: "479699168596"
    ECR_REPO: "api-newgate"          # <-- must match your ECR repository name
    CONTAINER_NAME: "api-newgate"     # <-- must match ECS task definition container name

phases:
  pre_build:
    commands:
      - set -e
      - aws --version
      - docker --version

      # ECR login
      - aws ecr get-login-password --region "$AWS_REGION" | docker login --username AWS --password-stdin "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"

      # Ensure repository exists (optional but prevents "does not exist" failures)
      - aws ecr describe-repositories --region "$AWS_REGION" --repository-names "$ECR_REPO" >/dev/null 2>&1
        || aws ecr create-repository --region "$AWS_REGION" --repository-name "$ECR_REPO"

      - REPOSITORY_URI="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO}"
      - COMMIT_HASH="$(echo ${CODEBUILD_RESOLVED_SOURCE_VERSION:-latest} | cut -c 1-7)"
      - IMAGE_TAG="${COMMIT_HASH:-latest}"

  build:
    commands:
      - chmod +x mvnw || true
      - ./mvnw clean package -DskipTests
      - docker build -t "${ECR_REPO}:${IMAGE_TAG}" .
      - docker tag "${ECR_REPO}:${IMAGE_TAG}" "${REPOSITORY_URI}:${IMAGE_TAG}"
      - docker tag "${ECR_REPO}:${IMAGE_TAG}" "${REPOSITORY_URI}:latest"

  post_build:
    commands:
      - docker push "${REPOSITORY_URI}:${IMAGE_TAG}"
      - docker push "${REPOSITORY_URI}:latest"
      - printf '[{"name":"%s","imageUri":"%s"}]' "$CONTAINER_NAME" "${REPOSITORY_URI}:${IMAGE_TAG}" > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
