version: 0.2

env:
  variables:
    AWS_REGION: us-east-1
    AWS_ACCOUNT_ID: "479699168596"
    ECR_REPO: "api-gateway"

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws --version
      - docker --version
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
      - REPOSITORY_URI=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO}
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:-latest}

  build:
    commands:
      - echo "Building api-gateway jar..."
      - cd api-gateway
      - mvn clean package -DskipTests
      - echo "Building Docker image..."
      - docker build -t ${ECR_REPO}:${IMAGE_TAG} .
      - docker tag ${ECR_REPO}:${IMAGE_TAG} ${REPOSITORY_URI}:${IMAGE_TAG}
      - docker tag ${ECR_REPO}:${IMAGE_TAG} ${REPOSITORY_URI}:latest

  post_build:
    commands:
      - echo "Pushing Docker image..."
      - docker push ${REPOSITORY_URI}:${IMAGE_TAG}
      - docker push ${REPOSITORY_URI}:latest
      - printf '[{"name":"%s","imageUri":"%s"}]' "${ECR_REPO}" "${REPOSITORY_URI}:${IMAGE_TAG}" > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
